name: Démo GitHub Actions
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Afficher un message
        run: echo Bonjour le monde !
